; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-2432S028R]
platform = espressif32
framework = arduino
board = esp32-2432S028R
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
monitor_filters = esp32_exception_decoder
board_build.partitions = min_spiffs.csv
build_flags = 
	-Ofast
	-Wall
	-I include
	-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
	-D LV_CONF_INCLUDE_SIMPLE
lib_deps =
    lvgl/lvgl@9.1.0
    rzeldent/esp32_smartdisplay@2.0.10
