// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: lightController

#ifndef UI_SCREEN_SCREEN1_H
#define UI_SCREEN_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_Screen1
extern void ui_Screen_Screen1_screen_init(void);
extern void ui_Screen_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen_Screen1;
extern lv_obj_t * ui_Screen1_Slider_Slider1;
extern lv_obj_t * ui_Screen1_Panel_Panel1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

