// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: lightController

#include "ui.h"

lv_obj_t * ui_Screen_Screen1 = NULL;
lv_obj_t * ui_Screen1_Slider_Slider1 = NULL;
lv_obj_t * ui_Screen1_Panel_Panel1 = NULL;
// event funtions

// build funtions

void ui_Screen_Screen1_screen_init(void)
{
    ui_Screen_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_Slider_Slider1 = lv_slider_create(ui_Screen_Screen1);
    lv_slider_set_value(ui_Screen1_Slider_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Screen1_Slider_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_Screen1_Slider_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Screen1_Slider_Slider1, 271);
    lv_obj_set_height(ui_Screen1_Slider_Slider1, 29);
    lv_obj_set_x(ui_Screen1_Slider_Slider1, 0);
    lv_obj_set_y(ui_Screen1_Slider_Slider1, -94);
    lv_obj_set_align(ui_Screen1_Slider_Slider1, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Screen1_Slider_Slider1,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Screen1_Slider_Slider1,
                                                                                  lv_obj_get_style_pad_right(ui_Screen1_Slider_Slider1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Screen1_Panel_Panel1 = lv_obj_create(ui_Screen_Screen1);
    lv_obj_set_width(ui_Screen1_Panel_Panel1, 320);
    lv_obj_set_height(ui_Screen1_Panel_Panel1, 190);
    lv_obj_set_x(ui_Screen1_Panel_Panel1, 0);
    lv_obj_set_y(ui_Screen1_Panel_Panel1, 25);
    lv_obj_set_align(ui_Screen1_Panel_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Screen1_Panel_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Screen1_Panel_Panel1, &ui_img_rainbowgradient_png, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen_Screen1_screen_destroy(void)
{
    if(ui_Screen_Screen1) lv_obj_del(ui_Screen_Screen1);

    // NULL screen variables
    ui_Screen_Screen1 = NULL;
    ui_Screen1_Slider_Slider1 = NULL;
    ui_Screen1_Panel_Panel1 = NULL;

}
