// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: defaultCYD

#include "ui.h"
#include <Arduino.h>

void mainButtonPressed(lv_event_t * e)
{
	Serial.println("Main button was pressed");
}
