// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: defaultCYD

#include "ui.h"

lv_obj_t * ui_Screen_Screen1 = NULL;
lv_obj_t * ui_Screen1_Button_Button1 = NULL;
lv_obj_t * ui_Screen1_Label_Label1 = NULL;
// event funtions
void ui_event_Screen1_Button_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        mainButtonPressed(e);
    }
}

// build funtions

void ui_Screen_Screen1_screen_init(void)
{
    ui_Screen_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_Button_Button1 = lv_button_create(ui_Screen_Screen1);
    lv_obj_set_width(ui_Screen1_Button_Button1, 100);
    lv_obj_set_height(ui_Screen1_Button_Button1, 50);
    lv_obj_set_align(ui_Screen1_Button_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Button_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Screen1_Button_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_Label_Label1 = lv_label_create(ui_Screen1_Button_Button1);
    lv_obj_set_width(ui_Screen1_Label_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen1_Label_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label_Label1, "Push Me");

    lv_obj_add_event_cb(ui_Screen1_Button_Button1, ui_event_Screen1_Button_Button1, LV_EVENT_ALL, NULL);

}

void ui_Screen_Screen1_screen_destroy(void)
{
    if(ui_Screen_Screen1) lv_obj_del(ui_Screen_Screen1);

    // NULL screen variables
    ui_Screen_Screen1 = NULL;
    ui_Screen1_Button_Button1 = NULL;
    ui_Screen1_Label_Label1 = NULL;

}
